// Generated by authany-deploy/docsite/scripts/gen_portal_docs_map.py from
// docsite/pages.json — do not edit by hand. Rebuild the docs site and re-run
// the generator when pages move.
export const AUTHANY_DOCS_ORIGIN = "https://docs.authany.com";

// upstream docs path (docs.authgear.com/<key>) -> path on docs.authany.com
export const UPSTREAM_DOCS_PATHS: Partial<Record<string, string>> = {
  "": "/",
  "admin-and-operations/user-management/account-valid-period":
    "/admin-and-operations/user-management/account-valid-period/",
  "admin-and-operations/user-management/disable-user":
    "/admin-and-operations/user-management/disable-user/",
  "admin/monitor": "/admin/monitor/",
  "admin/monitor/analytics": "/admin/monitor/analytics/",
  "admin/monitor/audit-log": "/admin/monitor/audit-log/",
  "admin/monitor/audit-log-for-admin-api-and-portal":
    "/admin/monitor/audit-log-for-admin-api-and-portal/",
  "admin/user-management": "/admin/user-management/",
  "admin/user-management/account-deletion":
    "/admin/user-management/account-deletion/",
  "admin/user-management/export-users-using-the-user-export-api":
    "/admin/user-management/export-users-using-the-user-export-api/",
  "admin/user-management/import-users-using-user-import-api":
    "/admin/user-management/import-users-using-user-import-api/",
  "admin/user-management/manage-users-roles-and-groups":
    "/admin/user-management/manage-users-roles-and-groups/",
  "admin/user-profiles": "/admin/user-profiles/",
  "admin/user-profiles/access-user-profiles":
    "/admin/user-profiles/access-user-profiles/",
  "admin/user-profiles/profile-custom-attributes":
    "/admin/user-profiles/profile-custom-attributes/",
  "admin/user-profiles/update-user-profile-on-sign-up-using-hooks":
    "/admin/user-profiles/update-user-profile-on-sign-up-using-hooks/",
  "admin/user-profiles/update-user-profiles":
    "/admin/user-profiles/update-user-profiles/",
  "admin/user-profiles/user-profile": "/admin/user-profiles/user-profile/",
  "api-reference/apis/oauth-2.0-and-openid-connect-oidc":
    "/reference/apis/oauth-2.0-and-openid-connect-oidc/",
  "authentication-and-access": "/authentication-and-access/",
  "authentication-and-access/authentication":
    "/authentication-and-access/authentication/",
  "authentication-and-access/authentication/add-authentication-to-any-web-page":
    "/authentication-and-access/authentication/add-authentication-to-any-web-page/",
  "authentication-and-access/authentication/add-email-magic-link-login":
    "/authentication-and-access/authentication/add-email-magic-link-login/",
  "authentication-and-access/authentication/anonymous-users":
    "/authentication-and-access/authentication/anonymous-users/",
  "authentication-and-access/authentication/biometric":
    "/authentication-and-access/authentication/biometric/",
  "authentication-and-access/authentication/custom-authentication-flow":
    "/authentication-and-access/authentication/custom-authentication-flow/",
  "authentication-and-access/authentication/disable-public-signup":
    "/authentication-and-access/authentication/disable-public-signup/",
  "authentication-and-access/authentication/enable-two-factor-authentication-2fa":
    "/authentication-and-access/authentication/enable-two-factor-authentication-2fa/",
  "authentication-and-access/authentication/how-to-use-social-enterprise-login-providers-without-authui":
    "/authentication-and-access/authentication/how-to-use-social-enterprise-login-providers-without-authui/",
  "authentication-and-access/authentication/how-to-use-the-oauth-2.0-state-parameter":
    "/authentication-and-access/authentication/how-to-use-the-oauth-2.0-state-parameter/",
  "authentication-and-access/authentication/local-cookie-based-web-setup":
    "/authentication-and-access/authentication/local-cookie-based-web-setup/",
  "authentication-and-access/authentication/passkeys":
    "/authentication-and-access/authentication/passkeys/",
  "authentication-and-access/authentication/passwordless-demo-user-for-apple-app-review":
    "/authentication-and-access/authentication/passwordless-demo-user-for-apple-app-review/",
  "authentication-and-access/authentication/passwords":
    "/authentication-and-access/authentication/passwords/",
  "authentication-and-access/authentication/passwords/forgot-reset-password-settings":
    "/authentication-and-access/authentication/passwords/forgot-reset-password-settings/",
  "authentication-and-access/authentication/passwords/how-to-handle-password-while-creating-accounts-for-users":
    "/authentication-and-access/authentication/passwords/how-to-handle-password-while-creating-accounts-for-users/",
  "authentication-and-access/authentication/passwords/password-expiry":
    "/authentication-and-access/authentication/passwords/password-expiry/",
  "authentication-and-access/authentication/passwords/password-policy":
    "/authentication-and-access/authentication/passwords/password-policy/",
  "authentication-and-access/authentication/passwords/reset-password-for-users":
    "/authentication-and-access/authentication/passwords/reset-password-for-users/",
  "authentication-and-access/authentication/phone-number-validation":
    "/authentication-and-access/authentication/phone-number-validation/",
  "authentication-and-access/authentication/reauthentication":
    "/authentication-and-access/authentication/reauthentication/",
  "authentication-and-access/authentication/whatsapp-otp-login":
    "/authentication-and-access/authentication/whatsapp-otp-login/",
  "authentication-and-access/sessions": "/authentication-and-access/sessions/",
  "authentication-and-access/single-sign-on":
    "/authentication-and-access/single-sign-on/",
  "authentication-and-access/single-sign-on/app2app-authorization":
    "/authentication-and-access/single-sign-on/app2app-authorization/",
  "authentication-and-access/single-sign-on/force-authgear-to-show-login-page":
    "/authentication-and-access/single-sign-on/force-authany-to-show-login-page/",
  "authentication-and-access/single-sign-on/oidc-provider":
    "/authentication-and-access/single-sign-on/oidc-provider/",
  "authentication-and-access/single-sign-on/pre-authenticated-urls":
    "/authentication-and-access/single-sign-on/pre-authenticated-urls/",
  "authentication-and-access/single-sign-on/single-sign-on-with-saml":
    "/authentication-and-access/single-sign-on/single-sign-on-with-saml/",
  "authentication-and-access/single-sign-on/single-sign-on-with-saml/saml-attribute-mapping":
    "/authentication-and-access/single-sign-on/single-sign-on-with-saml/saml-attribute-mapping/",
  "authentication-and-access/single-sign-on/single-sign-on-with-saml/use-authgear-as-saml-identity-provider-for-dropbox":
    "/authentication-and-access/single-sign-on/single-sign-on-with-saml/use-authany-as-saml-identity-provider-for-dropbox/",
  "authentication-and-access/single-sign-on/single-sign-on-with-saml/use-authgear-as-saml-identity-provider-for-salesforce":
    "/authentication-and-access/single-sign-on/single-sign-on-with-saml/use-authany-as-saml-identity-provider-for-salesforce/",
  "authentication-and-access/single-sign-on/sso-with-mobile-app-web-spa":
    "/authentication-and-access/single-sign-on/sso-with-mobile-app-web-spa/",
  "authentication-and-access/social-enterprise-login-providers":
    "/authentication-and-access/social-enterprise-login-providers/",
  "authentication-and-access/social-enterprise-login-providers/account-linking":
    "/authentication-and-access/social-enterprise-login-providers/account-linking/",
  "authentication-and-access/social-enterprise-login-providers/enterprise-login-providers":
    "/authentication-and-access/social-enterprise-login-providers/enterprise-login-providers/",
  "authentication-and-access/social-enterprise-login-providers/enterprise-login-providers/adfs":
    "/authentication-and-access/social-enterprise-login-providers/enterprise-login-providers/adfs/",
  "authentication-and-access/social-enterprise-login-providers/enterprise-login-providers/azureadb2c":
    "/authentication-and-access/social-enterprise-login-providers/enterprise-login-providers/azureadb2c/",
  "authentication-and-access/social-enterprise-login-providers/enterprise-login-providers/azureadv2":
    "/authentication-and-access/social-enterprise-login-providers/enterprise-login-providers/azureadv2/",
  "authentication-and-access/social-enterprise-login-providers/force-social-enterprise-login-providers-to-show-login-screen":
    "/authentication-and-access/social-enterprise-login-providers/force-social-enterprise-login-providers-to-show-login-screen/",
  "authentication-and-access/social-enterprise-login-providers/link-and-unlink-social-enterprise-provider-with-the-sdk":
    "/authentication-and-access/social-enterprise-login-providers/link-and-unlink-social-enterprise-provider-with-the-sdk/",
  "authentication-and-access/social-enterprise-login-providers/social-login-providers":
    "/authentication-and-access/social-enterprise-login-providers/social-login-providers/",
  "authentication-and-access/social-enterprise-login-providers/social-login-providers/apple":
    "/authentication-and-access/social-enterprise-login-providers/social-login-providers/apple/",
  "authentication-and-access/social-enterprise-login-providers/social-login-providers/facebook":
    "/authentication-and-access/social-enterprise-login-providers/social-login-providers/facebook/",
  "authentication-and-access/social-enterprise-login-providers/social-login-providers/github":
    "/authentication-and-access/social-enterprise-login-providers/social-login-providers/github/",
  "authentication-and-access/social-enterprise-login-providers/social-login-providers/google":
    "/authentication-and-access/social-enterprise-login-providers/social-login-providers/google/",
  "authentication-and-access/social-enterprise-login-providers/social-login-providers/linkedin":
    "/authentication-and-access/social-enterprise-login-providers/social-login-providers/linkedin/",
  "authentication-and-access/social-enterprise-login-providers/social-login-providers/wechat-mobile":
    "/authentication-and-access/social-enterprise-login-providers/social-login-providers/wechat-mobile/",
  "authentication-and-access/social-enterprise-login-providers/social-login-providers/wechat-web":
    "/authentication-and-access/social-enterprise-login-providers/social-login-providers/wechat-web/",
  "concepts/authgear-use-cases": "/concepts/authany-use-cases/",
  "concepts/how-authgear-integrate-with-your-applications":
    "/concepts/how-authany-integrate-with-your-applications/",
  "concepts/identity-fundamentals": "/concepts/identity-fundamentals/",
  "concepts/user-identity-and-authenticator":
    "/concepts/user-identity-and-authenticator/",
  customization: "/customization/",
  "customization/built-in-ui/user-settings":
    "/customization/ui-customization/built-in-ui/user-settings/",
  "customization/custom-domain": "/customization/custom-domain/",
  "customization/custom-providers": "/customization/custom-providers/",
  "customization/custom-providers/custom-email-provider":
    "/customization/custom-providers/custom-email-provider/",
  "customization/custom-providers/custom-sms-provider":
    "/customization/custom-providers/custom-sms-provider/",
  "customization/custom-providers/twilio":
    "/customization/custom-providers/twilio/",
  "customization/custom-providers/webhook-custom-script":
    "/customization/custom-providers/webhook-custom-script/",
  "customization/custom-ui": "/customization/ui-customization/custom-ui/",
  "customization/events-hooks": "/customization/events-hooks/",
  "customization/events-hooks/amr": "/customization/events-hooks/amr/",
  "customization/events-hooks/blocking-events":
    "/customization/events-hooks/blocking-events/",
  "customization/events-hooks/denohooks":
    "/customization/events-hooks/denohooks/",
  "customization/events-hooks/examples-common-use-cases":
    "/customization/events-hooks/examples-common-use-cases/",
  "customization/events-hooks/non-blocking-events":
    "/customization/events-hooks/non-blocking-events/",
  "customization/events-hooks/only-allow-signups-from-inside-the-corporate-network-using-hooks":
    "/customization/events-hooks/only-allow-signups-from-inside-the-corporate-network-using-hooks/",
  "customization/events-hooks/webhooks":
    "/customization/events-hooks/webhooks/",
  "customization/ui-customization/built-in-ui":
    "/customization/ui-customization/built-in-ui/",
  "customization/ui-customization/built-in-ui/branding":
    "/customization/ui-customization/built-in-ui/branding/",
  "customization/ui-customization/built-in-ui/customer-support-link":
    "/customization/ui-customization/built-in-ui/customer-support-link/",
  "customization/ui-customization/built-in-ui/localization":
    "/customization/ui-customization/built-in-ui/localization/",
  "customization/ui-customization/built-in-ui/privacy-policy-terms-of-service":
    "/customization/ui-customization/built-in-ui/privacy-policy-terms-of-service/",
  "customization/ui-customization/built-in-ui/user-settings":
    "/customization/ui-customization/built-in-ui/user-settings/",
  "customization/ui-customization/custom-email-and-sms-templates":
    "/customization/ui-customization/custom-email-and-sms-templates/",
  "customization/ui-customization/custom-ui":
    "/customization/ui-customization/custom-ui/",
  "customization/ui-customization/custom-ui/add-custom-login-signup-ui-to-native-apps":
    "/customization/ui-customization/custom-ui/add-custom-login-signup-ui-to-native-apps/",
  "customization/ui-customization/custom-ui/authentication-flow-api":
    "/customization/ui-customization/custom-ui/authentication-flow-api/",
  "customization/ui-customization/custom-ui/implement-a-custom-account-recovery-ui-using-authentication-flow-api":
    "/customization/ui-customization/custom-ui/implement-a-custom-account-recovery-ui-using-authentication-flow-api/",
  "customization/ui-customization/custom-ui/implement-authentication-flow-api-using-express":
    "/customization/ui-customization/custom-ui/implement-authentication-flow-api-using-express/",
  "customization/ui-customization/custom-ui/implement-authentication-flow-api-using-php":
    "/customization/ui-customization/custom-ui/implement-authentication-flow-api-using-php/",
  "customization/ui-customization/custom-ui/manually-link-oauth-provider-using-account-management-api":
    "/customization/ui-customization/custom-ui/manually-link-oauth-provider-using-account-management-api/",
  "customization/ui-customization/custom-ui/single-sign-on-continuation-with-custom-ui":
    "/customization/ui-customization/custom-ui/single-sign-on-continuation-with-custom-ui/",
  "customization/ui-customization/languages-and-localization":
    "/customization/ui-customization/languages-and-localization/",
  "deploy-on-your-cloud/auth-nginx": "/get-started/backend-api/nginx/",
  "faq-for-authentication": "/faq-for-authentication/",
  "faq-for-authentication/otp-test-mode":
    "/faq-for-authentication/otp-test-mode/",
  "get-started": "/get-started/start-building/",
  "get-started/5-minute-guide": "/get-started/5-minute-guide/",
  "get-started/ai-coding-tools": "/build-with-ai/ai-coding-tools/",
  "get-started/auth-for-mcp": "/get-started/auth-for-mcp/",
  "get-started/authentication-approach":
    "/get-started/authentication-approach/",
  "get-started/authentication-approach/cookie-based":
    "/get-started/authentication-approach/cookie-based/",
  "get-started/authentication-approach/token-based":
    "/get-started/authentication-approach/token-based/",
  "get-started/backend-api": "/get-started/backend-api/",
  "get-started/backend-api/backend-integration.md": "/get-started/backend-api/",
  "get-started/backend-api/jwt": "/get-started/backend-api/jwt/",
  "get-started/backend-api/nestjs": "/get-started/backend-api/nestjs/",
  "get-started/backend-api/nginx": "/get-started/backend-api/nginx/",
  "get-started/m2m-applications": "/get-started/m2m-applications/",
  "get-started/native-mobile-app": "/get-started/native-mobile-app/",
  "get-started/native-mobile-app/android":
    "/get-started/native-mobile-app/android/",
  "get-started/native-mobile-app/android/okhttp-interceptor-extension":
    "/get-started/native-mobile-app/android/okhttp-interceptor-extension/",
  "get-started/native-mobile-app/flutter":
    "/get-started/native-mobile-app/flutter/",
  "get-started/native-mobile-app/ionic":
    "/get-started/native-mobile-app/ionic/",
  "get-started/native-mobile-app/ionic-sdk":
    "/get-started/native-mobile-app/ionic/",
  "get-started/native-mobile-app/ios": "/get-started/native-mobile-app/ios/",
  "get-started/native-mobile-app/react-native":
    "/get-started/native-mobile-app/react-native/",
  "get-started/native-mobile-app/using-authgear-without-sdk-client-side":
    "/get-started/native-mobile-app/using-authany-without-sdk-client-side/",
  "get-started/native-mobile-app/xamarin":
    "/get-started/native-mobile-app/xamarin/",
  "get-started/oidc-provider":
    "/authentication-and-access/single-sign-on/oidc-provider/",
  "get-started/regular-web-app": "/get-started/regular-web-app/",
  "get-started/regular-web-app/asp.net-core-mvc":
    "/get-started/regular-web-app/asp.net-core-mvc/",
  "get-started/regular-web-app/express":
    "/get-started/regular-web-app/express/",
  "get-started/regular-web-app/java-spring-boot":
    "/get-started/regular-web-app/java-spring-boot/",
  "get-started/regular-web-app/laravel":
    "/get-started/regular-web-app/laravel/",
  "get-started/regular-web-app/nextjs": "/get-started/regular-web-app/nextjs/",
  "get-started/regular-web-app/php": "/get-started/regular-web-app/php/",
  "get-started/regular-web-app/python-flask-app":
    "/get-started/regular-web-app/python-flask-app/",
  "get-started/single-page-app": "/get-started/single-page-app/",
  "get-started/single-page-app/angular":
    "/get-started/single-page-app/angular/",
  "get-started/single-page-app/react": "/get-started/single-page-app/react/",
  "get-started/single-page-app/vue": "/get-started/single-page-app/vue/",
  "get-started/single-page-app/website":
    "/get-started/single-page-app/website/",
  "get-started/single-sign-on-with-saml":
    "/authentication-and-access/single-sign-on/single-sign-on-with-saml/",
  "get-started/start-building": "/get-started/start-building/",
  "how-to-guide/built-in-ui/auth-ui":
    "/customization/ui-customization/built-in-ui/",
  integration: "/integration/",
  "integration/add-custom-fields-to-a-jwt-access-token":
    "/integration/add-custom-fields-to-a-jwt-access-token/",
  "integration/directly-accessing-authgear-endpoint":
    "/integration/directly-accessing-authany-endpoint/",
  "integration/dynamic-client-registration":
    "/integration/dynamic-client-registration/",
  "integration/faq-for-integration": "/integration/faq-for-integration/",
  "integration/integration-with-other-software":
    "/integration/integration-with-other-software/",
  "integration/integration-with-other-software/authgear-firebase":
    "/integration/integration-with-other-software/authany-firebase/",
  "integration/integration-with-other-software/authgear-supabase":
    "/integration/integration-with-other-software/authany-supabase/",
  "integration/integration-with-other-software/user-analytics-by-google-tag-manager":
    "/integration/user-analytics-by-google-tag-manager/",
  "integration/mobile-apps": "/integration/mobile-apps/",
  "integration/mobile-apps/force-authentication-on-app-launch":
    "/integration/mobile-apps/force-authentication-on-app-launch/",
  "integration/mobile-apps/using-webview-to-open-the-authgear-ui":
    "/integration/mobile-apps/using-webview-to-open-the-authany-ui/",
  "integration/track-user-before-and-after-signup":
    "/integration/track-user-before-and-after-signup/",
  "integration/user-analytics-by-google-tag-manager":
    "/integration/user-analytics-by-google-tag-manager/",
  "integration/user-profiles/user-profile":
    "/admin/user-profiles/user-profile/",
  "integration/using-sdk-to-call-your-application-server":
    "/integration/using-sdk-to-call-your-application-server/",
  migration: "/migration/",
  "migration/bulk-migration": "/migration/bulk-migration/",
  "migration/rolling-migration": "/migration/rolling-migration/",
  "migration/zero-downtime-migration": "/migration/zero-downtime-migration/",
  reference: "/reference/",
  "reference/apis": "/reference/apis/",
  "reference/apis/admin-api": "/reference/apis/admin-api/",
  "reference/apis/admin-api/api-examples":
    "/reference/apis/admin-api/api-examples/",
  "reference/apis/admin-api/api-examples/generate-otp-code":
    "/reference/apis/admin-api/api-examples/generate-otp-code/",
  "reference/apis/admin-api/api-examples/search-for-users":
    "/reference/apis/admin-api/api-examples/search-for-users/",
  "reference/apis/admin-api/api-examples/update-users-picture":
    "/reference/apis/admin-api/api-examples/update-users-picture/",
  "reference/apis/admin-api/api-examples/update-users-standard-attributes":
    "/reference/apis/admin-api/api-examples/update-users-standard-attributes/",
  "reference/apis/admin-api/api-queries-and-mutations":
    "/reference/apis/admin-api/api-queries-and-mutations/",
  "reference/apis/admin-api/api-schema":
    "/reference/apis/admin-api/api-schema/",
  "reference/apis/admin-api/authentication-and-security":
    "/reference/apis/admin-api/authentication-and-security/",
  "reference/apis/admin-api/retrieving-users-using-admin-api":
    "/reference/apis/admin-api/retrieving-users-using-admin-api/",
  "reference/apis/admin-api/using-global-node-ids":
    "/reference/apis/admin-api/using-global-node-ids/",
  "reference/apis/authentication-flow-api":
    "/reference/apis/authentication-flow-api/",
  "reference/apis/oauth-2.0-and-openid-connect-oidc":
    "/reference/apis/oauth-2.0-and-openid-connect-oidc/",
  "reference/apis/oauth-2.0-and-openid-connect-oidc/supported-scopes":
    "/reference/apis/oauth-2.0-and-openid-connect-oidc/supported-scopes/",
  "reference/apis/oauth-2.0-and-openid-connect-oidc/userinfo":
    "/reference/apis/oauth-2.0-and-openid-connect-oidc/userinfo/",
  "reference/apis/user-export-api": "/reference/apis/user-export-api/",
  "reference/apis/user-import-api": "/reference/apis/user-import-api/",
  "reference/billing-faq": "/",
  "reference/glossary": "/reference/glossary/",
  "reference/rate-limits": "/reference/rate-limits/",
  "reference/rate-limits/account-lockout":
    "/reference/rate-limits/account-lockout/",
  "reference/tokens": "/reference/tokens/",
  "reference/tokens/jwt-access-token": "/reference/tokens/jwt-access-token/",
  "reference/tokens/m2m-tokens": "/reference/tokens/m2m-tokens/",
  "reference/tokens/refresh-token": "/reference/tokens/refresh-token/",
  security: "/security/",
  "security/bot-protection": "/security/bot-protection/",
  "security/brute-force-protection": "/security/brute-force-protection/",
  "security/fraud-protection": "/security/fraud-protection/",
  "security/ip-blocklist": "/security/ip-blocklist/",
  "security/redirect-uri": "/security/redirect-uri/",
  "security/sender-constraining": "/security/sender-constraining/",
  "strategies/email-login-link":
    "/authentication-and-access/authentication/add-email-magic-link-login/",
  "strategies/how-to-setup-sso-integrations":
    "/authentication-and-access/social-enterprise-login-providers/",
  troubleshooting: "/troubleshooting/",
  "troubleshooting/how-to-fix-cors-error":
    "/troubleshooting/how-to-fix-cors-error/",
  "troubleshooting/how-to-fix-subtlecrypto-digest-undefined-error-in-authgear-sdk":
    "/troubleshooting/how-to-fix-subtlecrypto-digest-undefined-error-in-authany-sdk/",
  "tutorials/spa/react": "/get-started/single-page-app/react/",
  "tutorials/spa/vue": "/get-started/single-page-app/vue/",
};
